### ISSUE TITLE
Sample mtx matrix?

### ISSUE THREAD

**Issue by 9Tempest** [xjtuiair-cag/gem5_dda#1]
Hi,
Where can we get a sample .mtx file for running this artifact?

**Comment by 4mod3** [comment]
You can get sparse matrix (_Matrix Market_ format) from real world in [SuiteSpare](https://sparse.tamu.edu/). 

FYI, matrixs are stored as CSC and you can transpose it to CSR format using some tools, e.g. Python-pandas.
Only "real" type of .mtx can be parsed by current serial_workloads and you can hack the code to support all kinds of types of mtx if you want.
