### ISSUE TITLE
Cannot initialize DMP without l3 cache

### ISSUE THREAD

**Issue by 9Tempest** [xjtuiair-cag/gem5_dda#2]
Hi, we are working on reproducing the result for PageRank, however, it shows that it runs index out of bound
```
# DMP benchmark init list
dmp_bench_list = {
    "spmv" : 0,
    "bfs" : 1,
    "sssp" : 2,
    "bc" : 3,
    "cc" : 4,
    "symgs" : 5,
    "pagerank" : 6
}

dmp_bench_init_pc = [
    [[0x400598, 0x4005b0], [0x4005b0, 0x4005bc], [0x4005b0]],
    [[0x400c70, 0x400c7c, 0x400ca0], [0x400c7c, 0x400ca0, 0x400ca4], [0x400ca0]]
    #[[0x400c70], [0x400c7c], [0x400c70]]
    #[[0x400c70, 0x400c7c], [0x400c7c, 0x400ca0], [0x400ca0]]
]
```
And the reason is that pagerank's init pc is not configured.
May I ask why we need to hack the PC? Also why pagerank's PC is missing?

**Comment by 4mod3** [comment]
We have separated the detection and prefetch generation of DMP by option _--dmp-init-bench_ and attribute [auto_detect](https://github.com/xjtuiair-cag/gem5_dda/blob/48a50ae2abb9c8178bbd051eded51ee14700448a/configs/common/CacheConfig.py#L315). This is for debugging and evaluating the overhead of detection.

The hint PCs listed here are only valid for spmv and bfs (I think) with the same binaries which we extracted the PC from. 
You can just remove _--dmp-init-bench_ in cmd and let DMP do auto-detection.
